apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: devops-tp
  labels:
    salle: ytrack-01
    app: devops-tp
spec:
  replicas: 4
  selector:
    matchLabels:
      salle: ytrack-01
  template:
    metadata:
      labels:
        salle: ytrack-01
    spec:
      containers:
        - name: echo
          image: registry.cluster.wik.cloud/public/echo
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-tp
spec:
  selector:
    salle: ytrack-01
  ports:
    - port: 9090
      targetPort: 8080
---
